# Generated by Django 4.2.26 on 2025-11-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kategorie', models.CharField(max_length=100)),
                ('art', models.CharField(blank=True, max_length=100)),
                ('aussaat_start_monat', models.PositiveSmallIntegerField(blank=True, help_text='Monat (1–12)', null=True)),
                ('aussaat_end_monat', models.PositiveSmallIntegerField(blank=True, help_text='Monat (1–12)', null=True)),
                ('info_url', models.URLField(blank=True)),
                ('bestand', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('einheit', models.CharField(choices=[('ANZ', 'Anzahl'), ('G', 'g')], default='ANZ', max_length=10)),
            ],
            options={
                'verbose_name': 'Sorte',
                'verbose_name_plural': 'Sorten',
                'ordering': ['kategorie', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PflanzplanEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveSmallIntegerField(help_text='Kalenderjahr, z.\u202fB. 2025')),
                ('aussaatdatum', models.DateField()),
                ('anzahl_samen', models.PositiveIntegerField()),
                ('art_der_aussaat', models.CharField(choices=[('ANZUCHT', 'Anzucht'), ('FREILAND', 'Freiland')], max_length=20)),
                ('anzuchtgefaess', models.CharField(blank=True, max_length=100)),
                ('pikierdatum', models.DateField(blank=True, null=True)),
                ('pflanzdatum', models.DateField(blank=True, null=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('sorte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pflanzplaene', to='garten.sorte')),
            ],
            options={
                'verbose_name': 'Pflanzplan-Eintrag',
                'verbose_name_plural': 'Pflanzplan-Einträge',
                'ordering': ['-jahr', 'aussaatdatum'],
            },
        ),
    ]
