# Generated by Django 4.2.26 on 2025-12-03 21:34

from django.db import migrations

def transfer_data(apps, schema_editor):
    Sorte = apps.get_model('garten', 'Sorte')
    Kategorie = apps.get_model('garten', 'Kategorie')
    Art = apps.get_model('garten', 'Art')

    for sorte in Sorte.objects.all():
        if sorte.kategorie:
            kategorie_obj, _ = Kategorie.objects.get_or_create(name=sorte.kategorie)
            sorte.kategorie_temp = kategorie_obj
        
        if sorte.art:
            art_obj, _ = Art.objects.get_or_create(name=sorte.art)
            sorte.art_temp = art_obj
        
        sorte.save()

class Migration(migrations.Migration):

    dependencies = [
        ('garten', '0002_art_kategorie_sorte_art_temp_sorte_kategorie_temp'),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
