# Generated by Django 4.2.26 on 2025-12-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garten', '0003_auto_20251203_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorte',
            name='art',
        ),
        migrations.RemoveField(
            model_name='sorte',
            name='kategorie',
        ),
        migrations.RenameField(
            model_name='sorte',
            old_name='art_temp',
            new_name='art',
        ),
        migrations.RenameField(
            model_name='sorte',
            old_name='kategorie_temp',
            new_name='kategorie',
        ),
    ]
