# Generated by Django 5.2.7 on 2026-02-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garten', '0004_remove_sorte_art_temp_remove_sorte_kategorie_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pflanzplaneintrag',
            name='jahr',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
