# Generated by Django 5.2.7 on 2026-02-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garten', '0005_alter_pflanzplaneintrag_jahr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pflanzplaneintrag',
            name='gps_genauigkeit',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Genauigkeit (m)'),
        ),
        migrations.AddField(
            model_name='pflanzplaneintrag',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='pflanzplaneintrag',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
    ]
