# Generated by Django 5.2.7 on 2025-11-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kategorie', models.CharField(blank=True, max_length=100)),
                ('art', models.CharField(blank=True, max_length=100)),
                ('aussaatzeitraum', models.CharField(blank=True, max_length=100)),
                ('beschreibung_url', models.URLField(blank=True, null=True)),
                ('bestand_menge', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('bestand_einheit', models.CharField(choices=[('pcs', 'Stück'), ('g', 'g'), ('kg', 'kg')], default='pcs', max_length=10)),
                ('notizen', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pflanzplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveSmallIntegerField()),
                ('aussaat_datum', models.DateField(blank=True, null=True)),
                ('aussaat_anzahl', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('aussaat_einheit', models.CharField(blank=True, choices=[('pcs', 'Stück'), ('g', 'g'), ('kg', 'kg')], max_length=10)),
                ('aussaat_art', models.CharField(blank=True, choices=[('anzucht', 'Anzucht'), ('freiland', 'Freiland'), ('direktsaat', 'Direktsaat')], max_length=20)),
                ('anzuchtgefaess', models.CharField(blank=True, max_length=100)),
                ('pikiert_datum', models.DateField(blank=True, null=True)),
                ('pflanz_datum', models.DateField(blank=True, null=True)),
                ('ernte_beschreibung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('sorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pflanzplaene', to='myapp.sorte')),
            ],
            options={
                'indexes': [models.Index(fields=['jahr'], name='myapp_pflan_jahr_cb02b5_idx')],
            },
        ),
    ]
